#!/usr/bin/env python3
"""Turn TTF fonts into anti-aliased 4-bit glyph tables for the Road Puck firmware.

Run from the repo root:  python3 tools/make_fonts.py
Writes firmware/RoadPuck/fonts.h. Needs Pillow (pip install pillow).
Only characters from space (0x20) to Z (0x5A) are included: the puck shows capitals only.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "firmware" / "RoadPuck" / "fonts.h"
FIRST, LAST = 0x20, 0x5A

# name, file, pixel size
FONTS = [
    ("F_STATUS", "Anton-Regular.ttf", 124),        # CLOSED / CLOSING / OPEN
    ("F_BIG", "Anton-Regular.ttf", 84),            # distance, e.g. 180 M
    ("F_ROAD", "BarlowCondensed-ExtraBold.ttf", 48),
    ("F_ROAD_S", "BarlowCondensed-ExtraBold.ttf", 38),
    ("F_SMALL", "BarlowCondensed-Bold.ttf", 32),
    ("F_TINY", "BarlowCondensed-SemiBold.ttf", 22),
]


def build(name, file, size):
    font = ImageFont.truetype(str(HERE / "fonts" / file), size)
    data = bytearray()
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch))
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        offset = len(data)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
            px = [(v * 15 + 127) // 255 for v in img.tobytes()]
            if len(px) % 2:
                px.append(0)
            for i in range(0, len(px), 2):
                data.append((px[i] << 4) | px[i + 1])
        glyphs.append((offset, w, h, adv, x0, y0))
    asc = -font.getbbox("H", anchor="ls")[1]  # cap height
    return data, glyphs, asc


def main():
    parts = [
        "// Generated by tools/make_fonts.py - do not edit by hand.",
        "// Fonts: Anton and Barlow Condensed, SIL Open Font License (see FONT-LICENSE-*.txt).",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "struct PuckGlyph { uint32_t offset; uint8_t w, h, adv; int8_t xo; int16_t yo; };",
        "struct PuckFont { const uint8_t *bits; const PuckGlyph *glyphs; uint8_t first, last; uint8_t capH; };",
        "",
    ]
    total = 0
    for name, file, size in FONTS:
        data, glyphs, cap = build(name, file, size)
        total += len(data) + len(glyphs) * 10
        parts.append(f"// {file} at {size}px, cap height {cap}px")
        parts.append(f"static const uint8_t {name}_bits[] = {{")
        for i in range(0, len(data), 32):
            parts.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i + 32]) + ",")
        parts.append("};")
        parts.append(f"static const PuckGlyph {name}_glyphs[] = {{")
        for code, (o, w, h, a, xo, yo) in zip(range(FIRST, LAST + 1), glyphs):
            label = chr(code) if chr(code) not in "\\'" else "\\" + chr(code)
            parts.append(f"  {{{o},{w},{h},{a},{xo},{yo}}}, // '{label}'")
        parts.append("};")
        parts.append(f"static const PuckFont {name} = {{{name}_bits, {name}_glyphs, 0x{FIRST:02x}, 0x{LAST:02x}, {cap}}};")
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT} ({total/1024:.0f} KB of font data)")


if __name__ == "__main__":
    main()
